"use strict";

// Prototype data only. No application database, files or services are accessed.
const initialRows = [
  {id:1,document:"Hóa đơn CMA-CG-201",invoice:"000321",container:"CMAU7312094",type:"Cước biển",amount:12750000,date:"2026-09-18",carrier:"CMA CGM",status:"valid",issue:"Thông tin đã đầy đủ."},
  {id:2,document:"Hóa đơn CMA-CG-201",invoice:"000321",container:"CMAU7312094",type:"Phí vệ sinh",amount:550000,date:"2026-09-18",carrier:"CMA CGM",status:"warning",issue:"Số tiền khác với bảng tổng hợp. Cần đối chiếu trước khi cập nhật."},
  {id:3,document:"Hóa đơn ONE-0926",invoice:"000849",container:"OOLU9182736",type:"Phí nâng hạ",amount:1200000,date:"",carrier:"Ocean Network Express",status:"error",issue:"Thiếu ngày hóa đơn. Hãy bổ sung trước khi xác nhận."},
  {id:4,document:"Hóa đơn ONE-0926",invoice:"000849",container:"OOLU9182736",type:"Phí lưu container",amount:2300000,date:"2026-09-20",carrier:"Ocean Network Express",status:"warning",issue:"Cần đối chiếu số tiền với bảng tổng hợp."},
  {id:5,document:"Hóa đơn DHL-886",invoice:"000886",container:"TGHU4826135",type:"Cước bộ",amount:8450000,date:"2026-09-21",carrier:"DHL Global Forwarding",status:"valid",issue:"Thông tin đã đầy đủ."},
  {id:6,document:"Hóa đơn DHL-886",invoice:"000886",container:"TGHU4826135",type:"Phí làm lệnh",amount:420000,date:"2026-09-21",carrier:"DHL Global Forwarding",status:"valid",issue:"Thông tin đã đầy đủ."}
];
const initialConflicts = [
  {id:1,title:"Phí vệ sinh · CMAU7312094",document:"Hóa đơn 000321 · Bảng tổng hợp tháng 09/2026",current:500000,incoming:550000,choice:"",context:"Ô tiền phí vệ sinh trong bảng tổng hợp đã có giá trị. Hãy chọn giá trị sẽ giữ lại."},
  {id:2,title:"Phí lưu container · OOLU9182736",document:"Hóa đơn 000849 · Bảng tổng hợp tháng 09/2026",current:2000000,incoming:2300000,choice:"",context:"Số tiền trên chứng từ khác giá trị đang có. Hãy đối chiếu hóa đơn trước khi chọn."}
];
const initialJobs = [
  {id:"qt-2451",number:"2451",company:"CMA CGM",amount:13300000,status:"pending",selected:false},
  {id:"qt-2452",number:"2452",company:"Ocean Network Express",amount:3500000,status:"pending",selected:false},
  {id:"qt-2448",number:"2448",company:"DHL Global Forwarding",amount:8870000,status:"done",selected:false}
];
const state = {
  page:"overview", rows:structuredClone(initialRows), conflicts:structuredClone(initialConflicts),jobs:structuredClone(initialJobs),
  selectedRow:3,reviewFilter:"all",reviewSearch:"",jobFilter:"all",confirmed:false,
  lastAction:"Đã tiếp nhận dữ liệu chứng từ lúc 09:30", modal:null
};
const titleMap = {overview:"Thao tác",review:"Kiểm tra dữ liệu",conflicts:"Xử lý chênh lệch",posting:"Nhập quyết toán",history:"Lịch sử",settings:"Cài đặt"};
if(titleMap[location.hash.slice(1)]) state.page=location.hash.slice(1);
const main = document.getElementById("main-content");
const modalRoot = document.getElementById("modal-root");
const money = value => new Intl.NumberFormat("vi-VN").format(value) + " đ";
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, character => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[character]));
const counts = () => ({error:state.rows.filter(row=>row.status==="error").length,warning:state.rows.filter(row=>row.status==="warning").length,valid:state.rows.filter(row=>row.status==="valid").length});
const pendingConflicts = () => state.conflicts.filter(item=>!item.choice).length;
const header = (kicker,title,subtitle,actions="") => `<div class="page-header"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${subtitle}</p></div><div class="page-actions">${actions}</div></div>`;
const badge = (status) => status==="error"?'<span class="pill error">Cần sửa</span>':status==="warning"?'<span class="pill warning">Cần xem lại</span>':status==="valid"?'<span class="pill success">Đã kiểm tra</span>':status==="done"?'<span class="pill success">Đã nhập</span>':'<span class="pill neutral">Chưa nhập</span>';

function renderOverview(){
  const count=counts();
  const fileState=state.confirmed?'<span class="pill success">Đã xác nhận</span>':count.error?`<span class="pill warning">${count.error} khoản cần sửa</span>`:'<span class="pill success">Sẵn sàng xác nhận</span>';
  main.innerHTML=header("QUY TRÌNH HIỆN TẠI","Tác vụ quyết toán","Bốn nhóm công việc quen thuộc. Chọn đúng tác vụ cần làm; trạng thái gần nhất nằm ngay tại mỗi nhóm.")+
  `<div class="workflow-stack">
    <section class="card workflow-card"><div class="workflow-number-large">01</div><div class="workflow-copy"><span class="flow-caption">BÓC TÁCH CHỨNG TỪ</span><h2>Mở trợ lý xử lý chứng từ</h2><p>Gửi chứng từ trong Trợ lý ảo và tải kết quả. Phần mềm tự tiếp nhận dữ liệu mới.</p><span class="flow-meta"><span class="status-dot"></span> Trợ lý đã được thiết lập</span></div><div class="workflow-actions"><button class="btn primary" data-action="assistant">Mở Trợ lý ảo</button><button class="btn" data-action="assistant-bk">Mở trợ lý bảng kê</button></div></section>
    <section class="card workflow-card"><div class="workflow-number-large">02</div><div class="workflow-copy"><span class="flow-caption">KIỂM TRA DỮ LIỆU</span><h2>Xem và sửa dữ liệu vừa tiếp nhận</h2><p>Chứng từ tháng 09/2026 · 6 khoản chi · Nhận lúc 09:30</p><div class="flow-meta">${fileState}<span class="flow-muted">${state.confirmed?"Đã kiểm tra xong lượt dữ liệu này.":"Kiểm tra và xác nhận trước khi nhập khoản chi vào BK."}</span></div></div><div class="workflow-actions"><button class="btn primary" data-page="review">Xem file bóc tách</button></div></section>
    <section class="card workflow-card workflow-card-excel"><div class="workflow-number-large">03</div><div class="workflow-copy"><span class="flow-caption">XỬ LÝ EXCEL</span><h2>Đồng bộ và cập nhật dữ liệu</h2><p>Ba tác vụ riêng như trong phần mềm hiện tại. Chọn đúng nguồn và đích cần xử lý.</p><div class="excel-action-list"><div class="excel-action"><div><strong>Hàng ngày → BK</strong><small>Cập nhật thông tin từ file Hàng ngày vào bảng kê.</small></div><span class="excel-state">Chưa chạy trong demo</span><button class="btn small primary" data-action="start-excel" data-kind="daily">Đồng bộ</button><button class="btn small ghost" data-action="view-excel" data-kind="daily">Xem lại</button></div><div class="excel-action"><div><strong>Khoản chi → BK</strong><small>Ghi các khoản chi đã xác nhận vào bảng kê.</small></div><span class="excel-state">${pendingConflicts()} khoản cần đối chiếu</span><button class="btn small primary" data-action="start-excel" data-kind="expense">Nhập vào BK</button><button class="btn small ghost" data-action="view-excel" data-kind="expense">Xem lại</button></div><div class="excel-action"><div><strong>BK → Thanh toán</strong><small>Chuyển dữ liệu từ bảng kê sang file thanh toán.</small></div><span class="excel-state">Chưa chạy trong demo</span><button class="btn small primary" data-action="start-excel" data-kind="payment">Đồng bộ</button><button class="btn small ghost" data-action="view-excel" data-kind="payment">Xem lại</button></div></div></div></section>
    <section class="card workflow-card"><div class="workflow-number-large">04</div><div class="workflow-copy"><span class="flow-caption">NHẬP LÊN PHẦN MỀM QUYẾT TOÁN</span><h2>Chọn và nhập các số quyết toán</h2><p>Chọn sheet BK, chọn một hoặc nhiều số quyết toán rồi bắt đầu nhập tự động.</p><span class="flow-meta"><span class="status-dot"></span> Công cụ nhập đã được thiết lập</span></div><div class="workflow-actions"><button class="btn primary" data-action="choose-rpa-sheet">Nhập PM quyết toán</button><button class="btn ghost" data-action="view-rpa">Xem dữ liệu đã gửi</button></div></section>
  </div>`;
}

function filteredRows(){let rows=state.rows.filter(row=>state.reviewFilter==="all"||row.status===state.reviewFilter);let query=state.reviewSearch.trim().toLocaleLowerCase("vi");return query?rows.filter(row=>`${row.document} ${row.invoice} ${row.container} ${row.type} ${row.carrier}`.toLocaleLowerCase("vi").includes(query)):rows;}
function reviewRowsMarkup(){let rows=filteredRows();return rows.length?rows.map(row=>`<tr data-row="${row.id}" class="${state.selectedRow===row.id?"selected":""}"><td><span class="primary-text">${escapeHtml(row.document)}</span><span class="secondary-text">${escapeHtml(row.invoice)}</span></td><td><span class="primary-text">${escapeHtml(row.type)}</span><span class="secondary-text">${escapeHtml(row.container)}</span></td><td class="money">${money(row.amount)}</td><td>${badge(row.status)}</td><td><button class="btn small" data-action="select-row" data-id="${row.id}">Xem chi tiết</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty"><strong>Không tìm thấy khoản chi</strong><p>Thử tìm bằng số hóa đơn, container hoặc loại phí.</p></td></tr>`;}
function renderDetail(){const row=state.rows.find(item=>item.id===state.selectedRow);if(!row)return '<div class="card detail-panel"><div class="empty">Chọn một khoản chi để xem chi tiết.</div></div>';const calloutClass=row.status==="valid"?"success":row.status==="error"?"error":"warning";return `<aside class="card detail-panel"><div class="detail-head"><div><h3>Chi tiết khoản chi</h3><small>${escapeHtml(row.document)}</small></div>${badge(row.status)}</div><div class="detail-pair"><span>Loại phí</span><strong>${escapeHtml(row.type)}</strong></div><div class="detail-pair"><span>Số tiền</span><strong>${money(row.amount)}</strong></div><div class="detail-rule"></div><p class="detail-section-label">CHỨNG TỪ VÀ ĐỐI CHIẾU</p><div class="detail-pair"><span>Số hóa đơn</span><strong>${escapeHtml(row.invoice)}</strong></div><div class="detail-pair"><span>Ngày hóa đơn</span><strong>${row.date?new Date(row.date+"T00:00:00").toLocaleDateString("vi-VN"):"Chưa có"}</strong></div><div class="detail-pair"><span>Container</span><strong>${escapeHtml(row.container)}</strong></div><div class="detail-pair"><span>Bên vận tải</span><strong>${escapeHtml(row.carrier)}</strong></div><div class="callout ${calloutClass}">${escapeHtml(row.issue)}</div><div class="detail-actions"><button class="btn primary" data-action="edit-row" data-id="${row.id}">Sửa thông tin</button>${row.status==="warning"?`<button class="btn" data-page="conflicts">Đối chiếu</button>`:""}</div></aside>`;}
function renderReview(){const count=counts(),visible=filteredRows();if(visible.length&&!visible.some(row=>row.id===state.selectedRow))state.selectedRow=visible[0].id;main.innerHTML=header("KIỂM TRA DỮ LIỆU","Kiểm tra khoản chi","Tập trung vào các khoản cần sửa, xem chi tiết bên cạnh và xác nhận khi dữ liệu đã sẵn sàng.",`<button class="btn" data-page="overview">Về trang Thao tác</button><button class="btn" data-action="show-source">Thông tin nguồn</button><button class="btn primary" data-action="confirm-review" ${count.error||state.confirmed?"disabled":""} title="${count.error?"Cần sửa hết các khoản lỗi trước khi xác nhận":state.confirmed?"Dữ liệu đã xác nhận":"Xác nhận dữ liệu đã kiểm tra"}">${state.confirmed?"Đã xác nhận":"Lưu và xác nhận"}</button>`)+
`<div class="card summary-strip"><div class="source"><strong>Chứng từ tháng 09/2026</strong><small>3 chứng từ · Tiếp nhận hôm nay lúc 09:30</small></div><span class="pill neutral">6 khoản chi</span><span class="pill error">${count.error} cần sửa</span><span class="pill warning">${count.warning} cần xem lại</span></div>
${count.error?`<div class="notice-bar"><span aria-hidden="true">●</span><div><strong>Cần sửa ${count.error} khoản chi trước khi xác nhận</strong><p>Chọn bộ lọc “Cần sửa”, mở từng khoản và bổ sung thông tin còn thiếu.</p></div></div>`:state.confirmed?'<div class="callout success">Dữ liệu đã xác nhận trong bản demo. Bạn có thể tiếp tục xem các khoản cần đối chiếu.</div>':'<div class="callout info">Không còn khoản bị chặn. Bạn có thể xác nhận dữ liệu sau khi xem các cảnh báo.</div>'}
<div class="work-layout"><section class="card"><div class="table-toolbar"><div class="search"><input id="review-search" type="search" placeholder="Tìm hóa đơn, container, loại phí…" value="${escapeHtml(state.reviewSearch)}" aria-label="Tìm khoản chi"></div><div class="segmented" aria-label="Lọc khoản chi"><button data-filter="all" class="${state.reviewFilter==="all"?"active":""}">Tất cả <span>${state.rows.length}</span></button><button data-filter="error" class="${state.reviewFilter==="error"?"active":""}">Cần sửa <span>${count.error}</span></button><button data-filter="warning" class="${state.reviewFilter==="warning"?"active":""}">Cần xem lại <span>${count.warning}</span></button></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Chứng từ</th><th>Khoản chi</th><th>Số tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody id="review-rows">${reviewRowsMarkup()}</tbody></table></div><div class="table-footer" id="review-footer">Đang hiển thị ${visible.length} trong ${state.rows.length} khoản chi · Chọn một dòng để xem chi tiết</div></section><div id="review-detail">${visible.length?renderDetail():'<aside class="card detail-panel"><div class="empty">Không có khoản chi trong bộ lọc này.</div></aside>'}</div></div>`;}

function renderConflicts(){let pending=pendingConflicts();main.innerHTML=header("ĐỐI CHIẾU DỮ LIỆU","Kiểm tra chênh lệch","So sánh số tiền từ chứng từ với số tiền đang có trước khi cập nhật bảng tổng hợp.",'<button class="btn" data-page="overview">Về trang Thao tác</button>')+
`<div class="notice-bar"><span aria-hidden="true">◎</span><div><strong>${pending?`Còn ${pending} khoản cần chọn cách xử lý`:"Đã có lựa chọn cho tất cả khoản chênh lệch"}</strong><p>Dữ liệu trong bảng tổng hợp chưa thay đổi. Bản demo chỉ mô phỏng bước xem trước quyết định.</p></div></div><div class="decision-grid"><section class="card decision-list">${state.conflicts.map(item=>`<div class="decision-row"><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.document)}</p><div class="compare"><div><small>ĐANG CÓ TRONG BẢNG</small><strong>${money(item.current)}</strong></div><div><small>TỪ CHỨNG TỪ</small><strong>${money(item.incoming)}</strong></div></div><div class="callout info" style="margin-bottom:0">${escapeHtml(item.context)}</div></div><div class="decision-control"><label for="conflict-${item.id}">Cách xử lý</label><select id="conflict-${item.id}" data-conflict="${item.id}"><option value="" ${!item.choice?"selected":""}>Chọn cách xử lý…</option><option value="keep" ${item.choice==="keep"?"selected":""}>Giữ số tiền đang có</option><option value="replace" ${item.choice==="replace"?"selected":""}>Dùng số tiền từ chứng từ</option><option value="skip" ${item.choice==="skip"?"selected":""}>Bỏ qua khoản này</option></select>${item.choice?'<span class="pill success">Đã chọn cách xử lý</span>':'<span class="pill warning">Chưa xử lý</span>'}</div></div>`).join("")}</section><aside class="card decision-aside"><h3>Trước khi cập nhật</h3><p>Kiểm tra các giá trị sẽ giữ lại và những giá trị sẽ thay đổi. Bạn có thể sửa lựa chọn ngay tại đây.</p><div class="workflow-line"><span class="workflow-number">1</span><div><strong>Xem chênh lệch</strong><small>Giá trị hiện tại và từ chứng từ</small></div></div><div class="workflow-line"><span class="workflow-number">2</span><div><strong>Chọn cách xử lý</strong><small>${state.conflicts.length-pending}/${state.conflicts.length} khoản đã chọn</small></div></div><div class="workflow-line"><span class="workflow-number">3</span><div><strong>Xem tóm tắt</strong><small>Kiểm tra trước khi cập nhật</small></div></div><button class="btn primary" data-action="preview-conflicts" ${pending?"disabled title=\"Chọn cách xử lý cho tất cả khoản\"":""}>Xem tóm tắt cập nhật</button><button class="btn ghost" data-page="overview">Về trang Thao tác</button></aside></div>`;}

function visibleJobs(){return state.jobFilter==="all"?state.jobs:state.jobs.filter(job=>job.status===state.jobFilter)}
function renderPosting(){const selected=state.jobs.filter(job=>job.selected);main.innerHTML=header("PHẦN MỀM QUYẾT TOÁN","Chọn quyết toán cần nhập","Xem số tiền và trạng thái của từng quyết toán trước khi bắt đầu nhập.",'<button class="btn" data-page="overview">Về trang Thao tác</button>')+
`<div class="card summary-strip"><div class="source"><strong>Bảng tổng hợp tháng 09/2026</strong><small>Nguồn dữ liệu · 3 số quyết toán trong bản demo</small></div><span class="pill success">2 chưa nhập</span><span class="pill neutral">1 đã nhập</span></div><div class="work-layout"><section class="card"><div class="table-toolbar"><div class="segmented"><button data-job-filter="all" class="${state.jobFilter==="all"?"active":""}">Tất cả</button><button data-job-filter="pending" class="${state.jobFilter==="pending"?"active":""}">Chưa nhập</button><button data-job-filter="done" class="${state.jobFilter==="done"?"active":""}">Đã nhập</button></div><div class="toolbar-right"><button class="btn small" data-action="select-pending">Chọn các số chưa nhập</button><button class="btn small" data-action="clear-jobs">Bỏ chọn</button></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th style="width:54px">Chọn</th><th>Số quyết toán</th><th>Bên vận tải</th><th>Tổng khoản chi</th><th>Trạng thái</th></tr></thead><tbody>${visibleJobs().map(job=>`<tr><td><input type="checkbox" data-job="${job.id}" ${job.selected?"checked":""} aria-label="Chọn quyết toán ${job.number}"></td><td class="primary-text">${job.number}</td><td>${escapeHtml(job.company)}</td><td class="money">${money(job.amount)}</td><td>${badge(job.status)}</td></tr>`).join("")}</tbody></table></div><div class="table-footer">Quyết toán đã nhập vẫn có thể chọn lại. Hãy kiểm tra kỹ trước khi chạy lại.</div></section><aside class="card decision-aside"><h3>Lượt nhập sắp thực hiện</h3><p>Kiểm tra số lượng và tổng tiền trước khi bắt đầu.</p><div class="detail-pair"><span>Đã chọn</span><strong>${selected.length} quyết toán</strong></div><div class="detail-pair"><span>Tổng khoản chi</span><strong>${money(selected.reduce((sum,job)=>sum+job.amount,0))}</strong></div>${selected.some(job=>job.status==="done")?'<div class="callout warning">Bạn đã chọn một quyết toán có trạng thái “Đã nhập”. Chạy lại có thể tạo thao tác nhập lặp.</div>':''}<button class="btn primary" data-action="preview-posting" ${selected.length?"":"disabled"}>Xem trước lượt nhập</button></aside></div>`;}

function renderHistory(){main.innerHTML=header("TRA CỨU","Lịch sử xử lý","Xem lại các lượt dữ liệu và trạng thái bằng tên dễ nhận biết.",'<button class="btn" data-page="overview">Về trang Thao tác</button>')+`<section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Lượt dữ liệu</th><th>Tiếp nhận</th><th>Số khoản chi</th><th>Tổng tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody><tr><td><span class="primary-text">Chứng từ tháng 09/2026</span><span class="secondary-text">3 chứng từ</span></td><td>Hôm nay · 09:30</td><td>6</td><td class="money">${money(state.rows.reduce((s,r)=>s+r.amount,0))}</td><td>${state.confirmed?'<span class="pill success">Đã xác nhận</span>':'<span class="pill warning">Đang kiểm tra</span>'}</td><td><button class="btn small" data-page="review">Mở dữ liệu</button></td></tr><tr><td><span class="primary-text">Chứng từ tháng 08/2026</span><span class="secondary-text">5 chứng từ</span></td><td>28/08/2026 · 14:20</td><td>12</td><td class="money">48.320.000 đ</td><td><span class="pill success">Đã xác nhận</span></td><td><button class="btn small" data-action="history-example">Xem chi tiết</button></td></tr></tbody></table></div></section>`;}

function renderSettings(){main.innerHTML=header("CÀI ĐẶT","Nguồn dữ liệu và kết nối","Xem vị trí lưu dữ liệu theo ngôn ngữ công việc. Các thiết lập kỹ thuật được thu gọn vào phần riêng.")+
`<div class="settings-grid"><section class="card settings-card"><h3>Bảng tổng hợp</h3><p>File dùng để nhận dữ liệu Hàng ngày và các khoản chi đã xác nhận.</p><div class="path">BK_Tong_hop_2026.xlsx</div><button class="btn" data-action="settings-demo">Chọn file khác</button></section><section class="card settings-card"><h3>Dữ liệu Hàng ngày</h3><p>Nguồn để cập nhật thông tin vận chuyển và bên vận tải.</p><div class="path">Hang_ngay_2026.xlsx</div><button class="btn" data-action="settings-demo">Chọn file khác</button></section><section class="card settings-card"><h3>Bảng thanh toán</h3><p>File nhận dữ liệu đã tổng hợp để tiếp tục thanh toán.</p><div class="path">Thanh_toan_2026.xlsx</div><button class="btn" data-action="settings-demo">Chọn file khác</button></section><section class="card settings-card"><h3>Kết nối trợ lý và nhập tự động</h3><p>Thông tin chạy công cụ được hiển thị khi cần thiết lập hoặc khắc phục sự cố.</p><div class="pill success">Đã thiết lập</div><div style="margin-top:15px"><button class="btn" data-action="technical">Xem thiết lập kỹ thuật</button></div></section></div>`;}

function render(){const navPage=["review","conflicts","posting"].includes(state.page)?"overview":state.page;document.querySelectorAll("[data-page].nav-item").forEach(button=>button.classList.toggle("active",button.dataset.page===navPage));document.getElementById("breadcrumb-current").textContent=state.page===navPage?titleMap[state.page]:`Thao tác / ${titleMap[state.page]}`;({overview:renderOverview,review:renderReview,conflicts:renderConflicts,posting:renderPosting,history:renderHistory,settings:renderSettings})[state.page]();}
function navigate(page){if(!titleMap[page])return;state.page=page;render();window.scrollTo({top:0,behavior:"smooth"});main.focus({preventScroll:true});}
function toast(message,title="Bản demo đã cập nhật",isError=false){const item=document.createElement("div");item.className=`toast${isError?" error":""}`;item.innerHTML=`<strong>${escapeHtml(title)}</strong>${escapeHtml(message)}`;document.getElementById("toast-root").append(item);setTimeout(()=>item.remove(),4300);}

function openModal(title,subtitle,body,buttons){state.modal=title;modalRoot.innerHTML=`<div class="modal-backdrop" role="presentation"><section class="modal" role="dialog" aria-modal="true" aria-label="${escapeHtml(title)}"><div class="modal-head"><div><h2>${escapeHtml(title)}</h2><p>${escapeHtml(subtitle)}</p></div><button class="close-x" data-action="close-modal" aria-label="Đóng">×</button></div><div class="modal-body">${body}</div><div class="modal-foot">${buttons}</div></section></div>`;modalRoot.querySelector(".modal button, .modal input, .modal select")?.focus();}
function closeModal(){state.modal=null;modalRoot.innerHTML="";}
function editRow(id){const row=state.rows.find(item=>item.id===Number(id));if(!row)return;openModal("Sửa thông tin khoản chi",`${row.document} · ${row.type}`,`<label for="edit-invoice">Số hóa đơn</label><input id="edit-invoice" type="text" value="${escapeHtml(row.invoice)}"><label for="edit-date">Ngày hóa đơn</label><input id="edit-date" type="date" value="${escapeHtml(row.date)}"><label for="edit-amount">Số tiền (đ)</label><input id="edit-amount" type="text" inputmode="numeric" value="${row.amount}"><div class="callout info">Hãy kiểm tra lại số tiền và ngày trên chứng từ gốc trước khi lưu.</div>`,`<button class="btn" data-action="close-modal">Hủy</button><button class="btn primary" data-action="save-row" data-id="${row.id}">Lưu thông tin</button>`);}
function saveRow(id){const row=state.rows.find(item=>item.id===Number(id));if(!row)return;const invoice=document.getElementById("edit-invoice").value.trim(),date=document.getElementById("edit-date").value,amount=Number(document.getElementById("edit-amount").value.replace(/[.\s,]/g,""));if(!invoice||!date||!Number.isSafeInteger(amount)||amount<0){toast("Điền số hóa đơn, ngày hóa đơn và số tiền hợp lệ.","Chưa lưu được",true);return;}row.invoice=invoice;row.date=date;row.amount=amount;state.confirmed=false;if(row.status==="error"){row.status="valid";row.issue="Thông tin đã được bổ sung. Hãy đối chiếu với chứng từ gốc trước khi xác nhận.";}state.lastAction=`Đã sửa ${row.type.toLowerCase()} của hóa đơn ${row.invoice}`;closeModal();render();toast("Thông tin khoản chi đã được cập nhật.");}
function confirmReview(){const count=counts();if(count.error){toast(`Còn ${count.error} khoản chi cần sửa.`,"Chưa thể xác nhận",true);return;}openModal("Xác nhận dữ liệu","Kiểm tra lại kết quả của lượt chứng từ này.",`<div class="detail-pair"><span>Số khoản chi</span><strong>${state.rows.length}</strong></div><div class="detail-pair"><span>Tổng tiền</span><strong>${money(state.rows.reduce((s,r)=>s+r.amount,0))}</strong></div><div class="detail-pair"><span>Cần xem lại</span><strong>${count.warning} khoản</strong></div><div class="callout warning">Việc xác nhận cho biết bạn đã kiểm tra dữ liệu. Bước cập nhật bảng tổng hợp được thực hiện sau.</div>`,`<button class="btn" data-action="close-modal">Quay lại kiểm tra</button><button class="btn primary" data-action="finish-review">Xác nhận ${state.rows.length} khoản chi</button>`);}
function previewConflicts(){if(pendingConflicts())return;const replacing=state.conflicts.filter(item=>item.choice==="replace");openModal("Tóm tắt cập nhật bảng tổng hợp","Các lựa chọn đã được tập hợp để bạn kiểm tra.",`<div class="detail-pair"><span>Dùng số tiền từ chứng từ</span><strong>${replacing.length} khoản</strong></div><div class="detail-pair"><span>Giữ số tiền đang có</span><strong>${state.conflicts.filter(item=>item.choice==="keep").length} khoản</strong></div><div class="detail-pair"><span>Bỏ qua</span><strong>${state.conflicts.filter(item=>item.choice==="skip").length} khoản</strong></div><div class="callout info">Bản demo chỉ minh họa màn xem trước. Không có file Excel nào được ghi.</div>`,`<button class="btn" data-action="close-modal">Quay lại chỉnh</button><button class="btn primary" data-action="finish-conflicts">Hoàn tất bản xem trước</button>`);}
function previewPosting(){const selected=state.jobs.filter(job=>job.selected);if(!selected.length)return;openModal("Xem trước lượt nhập quyết toán","Xác nhận các số quyết toán bạn vừa chọn.",`<div class="detail-pair"><span>Số quyết toán</span><strong>${selected.map(job=>job.number).join(", ")}</strong></div><div class="detail-pair"><span>Tổng khoản chi</span><strong>${money(selected.reduce((sum,job)=>sum+job.amount,0))}</strong></div>${selected.some(job=>job.status==="done")?'<div class="callout warning">Có quyết toán đã nhập trong lựa chọn. Hãy kiểm tra trước khi chạy lại.</div>':''}<div class="callout info">Bản demo không khởi chạy công cụ nhập và không gửi dữ liệu ra ngoài.</div>`,`<button class="btn" data-action="close-modal">Chỉnh lựa chọn</button><button class="btn primary" data-action="finish-posting">Xem trạng thái mô phỏng</button>`);}
function handleWorkflowAction(action,target){
  if(action==="start-excel"){
    const kind=target.dataset.kind;
    if(kind==="expense"&&!state.confirmed){openModal("Chưa có dữ liệu đã xác nhận","Bước nhập khoản chi vào BK cần dữ liệu đã kiểm tra.",'<div class="callout warning">Hãy mở file bóc tách ở nhóm Kiểm tra dữ liệu và xác nhận trước khi tiếp tục.</div>','<button class="btn" data-action="close-modal">Đóng</button><button class="btn primary" data-action="open-review">Mở bước kiểm tra</button>');return true;}
    const title={daily:"Đồng bộ Hàng ngày → BK",expense:"Nhập khoản chi → BK",payment:"Đồng bộ BK → Thanh toán"}[kind];
    if(!title)return false;
    const detail=kind==="expense"?"Chọn tháng BK để dò các khoản chi từ chứng từ đã xác nhận.":kind==="daily"?"Chọn tháng của file Hàng ngày và tháng BK tương ứng.":"Chọn tháng BK cần chuyển sang file Thanh toán.";
    openModal(title,"Chọn tháng dữ liệu trước khi phân tích.",`<p style="font-size:12px;color:#73868f;line-height:1.6">${detail}</p><label for="excel-month">Tháng xử lý</label><select id="excel-month"><option>Tháng 09/2026</option><option>Tháng 08/2026</option></select>`,`<button class="btn" data-action="close-modal">Hủy</button><button class="btn primary" data-action="analyze-excel" data-kind="${kind}">Phân tích</button>`);return true;
  }
  if(action==="analyze-excel"){
    const kind=target.dataset.kind;closeModal();if(kind==="expense"){navigate("conflicts");return true;}
    const label=kind==="daily"?"Hàng ngày → BK":"BK → Thanh toán";
    openModal(`Xem trước ${label}`,"Kết quả phân tích minh họa trước khi cập nhật.",'<div class="detail-pair"><span>Tháng xử lý</span><strong>09/2026</strong></div><div class="detail-pair"><span>Dòng dự kiến cập nhật</span><strong>6 dòng</strong></div><div class="callout info">Demo không ghi file Excel. Trong ứng dụng thật, bạn sẽ xem kết quả phân tích và xác nhận tại bước này.</div>','<button class="btn primary" data-action="close-modal">Đóng bản xem trước</button>');return true;
  }
  if(action==="open-review"){closeModal();navigate("review");return true;}
  if(action==="choose-rpa-sheet"){openModal("Chọn sheet BK","Bước đầu tiên của luồng nhập lên phần mềm quyết toán.",'<label for="rpa-sheet">Tháng trong bảng kê</label><select id="rpa-sheet"><option>T09 26 — Tháng 09/2026</option><option>T08 26 — Tháng 08/2026</option></select>','<button class="btn" data-action="close-modal">Hủy</button><button class="btn primary" data-action="open-rpa-selection">Tiếp tục chọn số quyết toán</button>');return true;}
  if(action==="open-rpa-selection"){closeModal();navigate("posting");return true;}
  if(action==="view-excel"){toast("Chưa có kết quả gần nhất trong dữ liệu demo.","Xem lại kết quả");return true;}
  if(action==="view-rpa"){toast("Chưa có lượt gửi dữ liệu trong bản demo.","Dữ liệu đã gửi");return true;}
  if(action==="assistant-bk"){toast("Đây là vị trí mở Trợ lý bảng kê trong phần mềm hiện tại.","Chức năng minh họa");return true;}
  return false;
}
function handleAction(action,target){if(handleWorkflowAction(action,target))return;if(action==="close-modal"){closeModal();return;}if(action==="select-row"){state.selectedRow=Number(target.dataset.id);renderReview();return;}if(action==="edit-row"){editRow(target.dataset.id);return;}if(action==="save-row"){saveRow(target.dataset.id);return;}if(action==="confirm-review"){confirmReview();return;}if(action==="finish-review"){state.confirmed=true;state.lastAction="Đã xác nhận dữ liệu khoản chi trong bản demo";closeModal();render();toast("Dữ liệu đã xác nhận trong bản demo.");return;}if(action==="preview-conflicts"){previewConflicts();return;}if(action==="finish-conflicts"){state.lastAction="Đã xem tóm tắt các khoản chênh lệch";closeModal();navigate("overview");toast("Đã hoàn tất bản xem trước. File Excel chưa thay đổi.");return;}if(action==="preview-posting"){previewPosting();return;}if(action==="finish-posting"){closeModal();toast("Đây là mô phỏng. Trạng thái nhập thực tế chưa thay đổi.","Đã xem trước lượt nhập");return;}if(action==="select-pending"){state.jobs.forEach(job=>job.selected=job.status==="pending");renderPosting();return;}if(action==="clear-jobs"){state.jobs.forEach(job=>job.selected=false);renderPosting();return;}if(action==="view-history"){navigate("history");return;}if(action==="show-source"){openModal("Thông tin nguồn dữ liệu","Dùng khi cần đối chiếu hoặc liên hệ hỗ trợ.",`<div class="detail-pair"><span>Nguồn dữ liệu</span><strong>3 chứng từ tháng 09/2026</strong></div><div class="detail-pair"><span>Tiếp nhận</span><strong>Hôm nay · 09:30</strong></div><div class="detail-pair"><span>Định dạng gốc</span><strong>JSON từ trợ lý chứng từ</strong></div>`,`<button class="btn primary" data-action="close-modal">Đóng</button>`);return;}if(action==="technical"){openModal("Thiết lập kỹ thuật","Thông tin dành cho lúc cài đặt hoặc kiểm tra sự cố.",`<div class="detail-pair"><span>Trợ lý chứng từ</span><strong>Đã kết nối</strong></div><div class="detail-pair"><span>Nhập quyết toán</span><strong>Đã thiết lập</strong></div><div class="callout info">Trong ứng dụng thật, đây là nơi có thể xem đường dẫn công cụ và trạng thái kết nối khi cần hỗ trợ.</div>`,`<button class="btn primary" data-action="close-modal">Đóng</button>`);return;}if(action==="assistant"||action==="settings-demo"||action==="history-example"){toast("Tác vụ này được minh họa bằng dữ liệu mẫu; chưa kết nối ứng dụng thật.","Chức năng minh họa");}}

document.addEventListener("click",event=>{const button=event.target.closest("button");if(button){if(button.dataset.page){navigate(button.dataset.page);return;}if(button.dataset.action){handleAction(button.dataset.action,button);return;}if(button.dataset.filter){state.reviewFilter=button.dataset.filter;renderReview();return;}if(button.dataset.jobFilter){state.jobFilter=button.dataset.jobFilter;renderPosting();return;}}const row=event.target.closest("tr[data-row]");if(row){state.selectedRow=Number(row.dataset.row);renderReview();}});
document.addEventListener("change",event=>{const target=event.target;if(target.matches("select[data-conflict]")){const conflict=state.conflicts.find(item=>item.id===Number(target.dataset.conflict));if(conflict){conflict.choice=target.value;renderConflicts();}}if(target.matches("input[data-job]")){const job=state.jobs.find(item=>item.id===target.dataset.job);if(job){job.selected=target.checked;renderPosting();}}});
document.addEventListener("input",event=>{if(event.target.id!=="review-search")return;state.reviewSearch=event.target.value;const cursor=event.target.selectionStart;renderReview();const next=document.getElementById("review-search");next.focus();next.setSelectionRange(cursor,cursor);});
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&state.modal)closeModal();});
modalRoot.addEventListener("click",event=>{if(event.target.classList.contains("modal-backdrop"))closeModal();});
render();
